from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 465)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(722, 465))
        MainWindow.setMaximumSize(QtCore.QSize(722, 465))
        MainWindow.setSizeIncrement(QtCore.QSize(722, 577))
        MainWindow.setStyleSheet("background-color: rgb(255, 244, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(10, 10, 701, 451))
        self.main_frame.setMinimumSize(QtCore.QSize(701, 401))
        self.main_frame.setMaximumSize(QtCore.QSize(701, 500))
        self.main_frame.setStyleSheet("background-color: rgb(255, 244, 245);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.logo_frame = QtWidgets.QFrame(self.main_frame)
        self.logo_frame.setGeometry(QtCore.QRect(10, 10, 681, 91))
        self.logo_frame.setStyleSheet("background-color: rgb(255, 244, 245);")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.label_2 = QtWidgets.QLabel(self.logo_frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 101, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("logo.jpg"))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.logo_frame)
        self.label.setGeometry(QtCore.QRect(130, 10, 541, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 244, 245);")
        self.label.setObjectName("label")
        self.basic_frame = QtWidgets.QFrame(self.main_frame)
        self.basic_frame.setGeometry(QtCore.QRect(0, 100, 691, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.basic_frame.setFont(font)
        self.basic_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.basic_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.basic_frame.setObjectName("basic_frame")
        self.link_frame = QtWidgets.QFrame(self.basic_frame)
        self.link_frame.setGeometry(QtCore.QRect(10, 10, 671, 61))
        self.link_frame.setStyleSheet("")
        self.link_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.link_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.link_frame.setObjectName("link_frame")
        self.lineEdit = QtWidgets.QLineEdit(self.link_frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.process_button = QtWidgets.QPushButton(self.link_frame)
        self.process_button.setGeometry(QtCore.QRect(600, 10, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.process_button.setFont(font)
        self.process_button.setStyleSheet("")
        self.process_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.process_button.setIcon(icon)
        self.process_button.setIconSize(QtCore.QSize(35, 35))
        self.process_button.setObjectName("process_button")
        self.frame_2 = QtWidgets.QFrame(self.basic_frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 80, 661, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(300, 50, 361, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.file_size_label = QtWidgets.QLabel(self.frame)
        self.file_size_label.setGeometry(QtCore.QRect(90, 50, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_size_label.setFont(font)
        self.file_size_label.setText("")
        self.file_size_label.setObjectName("file_size_label")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(0, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border-color: rgb(99, 229, 0);")
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.file_size_label_2 = QtWidgets.QLabel(self.frame)
        self.file_size_label_2.setGeometry(QtCore.QRect(90, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_size_label_2.setFont(font)
        self.file_size_label_2.setText("")
        self.file_size_label_2.setObjectName("file_size_label_2")
        self.add_button = QtWidgets.QPushButton(self.frame)
        self.add_button.setGeometry(QtCore.QRect(220, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 229, 0);")
        self.add_button.setObjectName("add_button")
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setGeometry(QtCore.QRect(20, 210, 491, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.title_label = QtWidgets.QLabel(self.frame_2)
        self.title_label.setGeometry(QtCore.QRect(80, 10, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_label.setFont(font)
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.thumbnail_label = QtWidgets.QLabel(self.frame_2)
        self.thumbnail_label.setGeometry(QtCore.QRect(20, 50, 261, 141))
        self.thumbnail_label.setText("")
        self.thumbnail_label.setObjectName("thumbnail_label")
        self.download_button = QtWidgets.QPushButton(self.frame_2)
        self.download_button.setGeometry(QtCore.QRect(520, 200, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.download_button.setFont(font)
        self.download_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 229, 0);")
        self.download_button.setObjectName("download_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "YouTube Downloader"))
        self.lineEdit.setToolTip(_translate("MainWindow", "Paste your link here"))
        self.label_4.setText(_translate("MainWindow", "File size:"))
        self.comboBox.setToolTip(_translate("MainWindow", "Select your stream"))
        self.label_5.setText(_translate("MainWindow", "Length:"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.label_3.setText(_translate("MainWindow", "Title:"))
        self.download_button.setText(_translate("MainWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
